# Generated by Django 3.0 on 2019-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Pending'), (2, 'Closed')]),
        ),
    ]
