# Generated by Django 2.1.7 on 2019-03-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_component_contenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='contentType',
        ),
    ]
